services:
  - type: web
    name: enhanced-experience-platform
    env: node
    buildCommand: pnpm install --frozen-lockfile
    startCommand: node dist/server.js
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production

